coverage:
  precision: 2
  status:
    project:
      default:
        target: 70%
        threshold: 22% # TODO: Increase coverage to >= 90%

    patch:
      default:
        target: 90%
        threshold: 20%

ignore:
  - "**/tests/**"
  - "**/examples/**"
