coverage:
  precision: 2
  status:
    project:
      default:
        target: 90%
        threshold: 20%

    patch:
      default:
        target: 90%
        threshold: 20%

    patch:
      default:
        target: 90%
        threshold: 20%

ignore:
  - "**/tests/**"
  - "**/examples/**"
