// AUTO-GENERATED - do not hand-edit.
// Source: scripts/gaussian_codegen/cdf/derive.py + scripts/gaussian_codegen/cdf/emit_coefficients.py

/// Numerator and denominator coefficients for the rational `N(z) / D(z)`
/// standard-normal CDF approximation on the central domain `[0, 6.109410205]`.
/// The coefficients are chosen to minimize the number of incorrectly-rounded
/// outputs of the exact on-chain integer evaluation (not the continuous
/// approximation error); see `scripts/gaussian_codegen/`. All values are
/// sign-magnitude pairs at CDF WAD (`10^36`) scale, indexed in ascending power
/// order (index 0 is the constant term).
///
/// Accessors return the underlying `vector<u128>` / `vector<bool>` constants so
/// callers can bind them to a local once per CDF evaluation and index locally
/// inside the Horner loop - avoiding a fresh constant load on every iteration.
///
/// See `cdf` for the consumer API. This module is regenerated by the codegen
/// in `scripts/gaussian_codegen/cdf/`; do not hand-edit.
module openzeppelin_fp_math::cdf_coefficients;

// === Constants ===

const NUM_MAGS: vector<u128> = vector[
    499_999_999_999_999_999_999_999_999_649_301_219, 198_743_854_931_599_762_830_285_876_714_358_413,
    18_311_175_884_402_537_878_114_553_918_424_714, 13_786_475_527_560_591_844_940_476_467_729_192,
    11_239_926_398_407_464_181_892_059_567_005_407, 693_331_651_502_996_078_816_592_886_377_189,
    86_868_756_777_874_966_976_776_178_466_965, 291_982_848_428_993_072_562_138_321_260_481,
    52_854_927_304_561_731_581_414_625_031_385, 8_833_289_889_386_681_282_265_363_992_952,
];

const NUM_NEGS: vector<bool> = vector[
    false, false, true, false, false, true, true, false, true, false,
];

const DEN_MAGS: vector<u128> = vector[
    1_000_000_000_000_000_000_000_000_000_000_000_000,
    400_396_854_868_447_734_576_864_530_214_141_721, 282_848_217_761_273_362_671_640_622_617_442_351,
    65_127_492_275_631_447_848_189_846_539_125_143, 21_204_037_950_107_365_173_411_742_641_435_109,
    654_713_008_708_425_020_732_867_235_638_070, 292_134_456_349_340_809_713_400_393_340_228,
    322_184_095_233_588_475_607_210_523_427_169, 54_824_274_761_785_728_881_942_414_809_685,
    8_884_387_266_593_344_130_831_401_300_578,
];

const DEN_NEGS: vector<bool> = vector[
    false, true, false, true, false, true, true, false, true, false,
];

/// Saturation threshold |z| at the raw `10^9` scale: inputs with |z| ≥ this
/// saturate to the endpoint (0 for negative z, 10^9 for positive z) instead of
/// consulting the rational. Single source of truth for the central-domain
/// bound, consumed by `cdf::cdf_nonneg_raw`.
const MAX_Z_RAW: u128 = 6_109_410_205;

// === Package Functions ===

/// Numerator magnitudes (ascending power order).
public(package) fun cdf_num_mags(): vector<u128> { NUM_MAGS }

/// Numerator sign flags (ascending power order); index `i` paired with `cdf_num_mags()[i]`.
public(package) fun cdf_num_negs(): vector<bool> { NUM_NEGS }

/// Denominator magnitudes (ascending power order).
public(package) fun cdf_den_mags(): vector<u128> { DEN_MAGS }

/// Denominator sign flags (ascending power order); index `i` paired with `cdf_den_mags()[i]`.
public(package) fun cdf_den_negs(): vector<bool> { DEN_NEGS }

/// Saturation threshold |z| at the raw `10^9` scale (`6_109_410_205`).
public(package) fun max_z_raw(): u128 { MAX_Z_RAW }
