// AUTO-GENERATED - do not hand-edit.
// Source: scripts/gaussian_codegen/pdf/derive.py + scripts/gaussian_codegen/pdf/emit_coefficients.py

/// Numerator and denominator coefficients for the rational `N(z) / D(z)`
/// standard-normal PDF approximation on the central domain `[0, 6.402729806]`.
/// The coefficients are chosen to minimize the number of incorrectly-rounded
/// outputs of the exact on-chain integer evaluation (not the continuous
/// approximation error); see `scripts/gaussian_codegen/`. All values are
/// sign-magnitude pairs at PDF WAD (`10^36`) scale, indexed in ascending power
/// order (index 0 is the constant term).
///
/// Accessors return the underlying `vector<u128>` / `vector<bool>` constants so
/// callers can bind them to a local once per PDF evaluation and index locally
/// inside the Horner loop - avoiding a fresh constant load on every iteration.
///
/// See `pdf` for the consumer API. This module is regenerated by the codegen
/// in `scripts/gaussian_codegen/pdf/`; do not hand-edit.
module openzeppelin_fp_math::pdf_coefficients;

// === Constants ===

const NUM_MAGS: vector<u128> = vector[
    398_942_280_401_915_824_010_581_683_619_408_349, 242_400_861_759_065_014_139_516_317_165_105_341,
    8_406_745_954_184_064_828_799_273_563_982_086, 39_495_218_004_106_100_066_950_178_920_962_117,
    9_235_044_401_195_015_228_677_508_379_866_948, 961_022_421_401_175_848_626_248_781_810_666,
    836_207_698_880_890_099_197_325_398_915_436, 176_069_026_218_484_945_235_086_675_128_989,
    18_914_035_494_901_363_757_376_122_655_258, 1_066_513_293_312_797_055_400_876_817_225,
    25_176_059_188_798_123_466_595_220_147,
];

const NUM_NEGS: vector<bool> = vector[
    false, true, true, false, true, true, false, true, false, true, false,
];

const DEN_MAGS: vector<u128> = vector[
    1_000_000_000_000_000_000_000_000_000_000_000_000,
    607_608_853_879_456_935_405_054_954_340_648_527, 478_927_435_281_286_194_375_982_876_419_515_441,
    204_804_923_901_879_678_602_456_693_478_871_766, 91_316_846_115_393_529_986_139_987_774_931_520,
    28_866_561_899_570_541_251_616_767_925_831_159, 8_733_773_968_348_065_653_146_376_162_648_476,
    1_945_420_074_765_128_841_627_339_991_199_136, 378_717_902_851_432_873_806_537_122_713_584,
    46_710_700_718_059_757_047_359_842_350_769, 4_063_225_493_688_261_992_273_503_206_754,
];

const DEN_NEGS: vector<bool> = vector[
    false, true, false, true, false, true, false, true, false, true, false,
];

/// Saturation threshold |z| at the raw `10^9` scale: inputs with |z| ≥ this
/// saturate to `0` (the density has decayed below the `10^-9` output resolution)
/// instead of consulting the rational. Single source of truth for the
/// central-domain bound, consumed by `pdf::pdf_nonneg_raw`.
const MAX_Z_RAW: u128 = 6_402_729_806;

// === Package Functions ===

/// Numerator magnitudes (ascending power order).
public(package) fun pdf_num_mags(): vector<u128> { NUM_MAGS }

/// Numerator sign flags (ascending power order); index `i` paired with `pdf_num_mags()[i]`.
public(package) fun pdf_num_negs(): vector<bool> { NUM_NEGS }

/// Denominator magnitudes (ascending power order).
public(package) fun pdf_den_mags(): vector<u128> { DEN_MAGS }

/// Denominator sign flags (ascending power order); index `i` paired with `pdf_den_mags()[i]`.
public(package) fun pdf_den_negs(): vector<bool> { DEN_NEGS }

/// Saturation threshold |z| at the raw `10^9` scale (`6_402_729_806`).
public(package) fun max_z_raw(): u128 { MAX_Z_RAW }
